config/routes.rb
Rails.application.routes.draw do

  resources :topics
  namespace :api, defaults: {format: 'json'} do
    namespace :v1 do
      resources :users
    end
  end

  root "pages#homepage"
  get '/home',to: 'pages#homepage'
  get '/help', to: 'pages#helppage'
  get '/about', to: 'pages#aboutpage'
  get '/contact',to: 'pages#contactpage'
  get '/signup',to: 'users#new'
  post '/signup',  to: 'users#create'
  patch '/makeadmin', to: 'users#make_admin', as: 'makeadmin'
  get '/login', to:  'sessions#new'
  post '/login', to:  'sessions#create'
  delete  '/logout', to:  'sessions#destroy'
  resources :account_activations, only: [:edit]
  resources :users  do
    member do
      get :following # like users/1/following
      get :followers
    end
  end
  resources :password_resets, only: [:new,:create,:edit,:update]
  resources :micro_posts, only: [:create,:destroy]
  get '/micro_posts', to: 'micro_posts#index', :defaults => { :format => 'json' }
  get '/show_users_json', to: 'users#show_users_json', :defaults => { :format => 'json' }
  get '/show_user_json/:id', to: 'users#show_user_json', :defaults => { :format => 'json' }
  resources :relationships, only: [:create,:destroy]
  resources :ratings, only: [:create]

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

end

app/models/topic.rb
class Topic < ApplicationRecord
  has_many :micro_posts
end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
  before_action :set_topic, only: [:show, :edit, :update, :destroy]
  load_and_authorize_resource

  respond_to :html

  def index
    @topics = Topic.all
    # authorize! :index, @topics
  end

  def show
    @topic = Topic.find(params[:id])
    @microposts = @topic.micro_posts.paginate(page: params[:page],per_page: 10)
    authorize! :show, @topic
  end

  def new
    @topic = Topic.new
    # respond_with(@topic)
    # authorize! :new, @topic
  end

  def edit
  end

  def create
    @topic = Topic.new(topic_params)
    @topic.save
    respond_with(@topic)
    authorize! :create, @topic

  end

  def update
    @topic.update(topic_params)
    respond_with(@topic)
    authorize! :update, @topic

  end

  def destroy
    @topic.destroy
    respond_with(@topic)
    authorize! :destroy, @topic

  end

  private
    def set_topic
      @topic = Topic.find(params[:id])
    end

    def topic_params
      params.require(:topic).permit(:name)
    end
end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/views/topics/_form.html.erb
<%= form_with(model: topic, local: true) do |form| %>
  <% if topic.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(topic.errors.count, "error") %> prohibited this topic from being saved:</h2>

      <ul>
      <% topic.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :topic_name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/topics/edit.html.erb
<h1>Editing Topic</h1>
<% if can? :edit, Topic %>
    <%= render 'form', topic: @topic %>
<% end %>


<%= link_to 'Show', @topic %> |
<%= link_to 'Back', topics_path %>

app/views/topics/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Topics</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @topics.each do |topic| %>
      <tr>
        <td><%= topic.name %></td>
        <td><%= link_to 'Show', topic %></td>
        <td><%= link_to 'Edit', edit_topic_path(topic) %></td>
        <% if can? :destroy, Topic %>
            <td><%= link_to 'Destroy', topic, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Topic', new_topic_path %>

app/views/topics/new.html.erb
<h1>New Topic</h1>

<% if can? :create, Topic %>
    <%= render 'form', topic: @topic %>
<% end %>

<%= link_to 'Back', topics_path %>

app/views/topics/show.html.erb
<% provide(:heading , "#{@topic.name} Feed") %>
<%= render 'shared/show_feeds' %>

<%= link_to 'Edit', edit_topic_path(@topic) %> |
<%= link_to 'Back', topics_path %>