config/routes.rb
Rails.application.routes.draw do

  resources :topics
  namespace :api, defaults: {format: 'json'} do
    namespace :v1 do
      resources :users
    end
  end

  root "pages#homepage"
  get '/home',to: 'pages#homepage'
  get '/help', to: 'pages#helppage'
  get '/about', to: 'pages#aboutpage'
  get '/contact',to: 'pages#contactpage'
  get '/signup',to: 'users#new'
  post '/signup',  to: 'users#create'
  patch '/makeadmin', to: 'users#make_admin', as: 'makeadmin'
  get '/login', to:  'sessions#new'
  post '/login', to:  'sessions#create'
  delete  '/logout', to:  'sessions#destroy'
  resources :account_activations, only: [:edit]
  resources :users  do
    member do
      get :following # like users/1/following
      get :followers
    end
  end
  resources :password_resets, only: [:new,:create,:edit,:update]
  resources :micro_posts, only: [:create,:destroy]
  get '/micro_posts', to: 'micro_posts#index', :defaults => { :format => 'json' }
  get '/show_users_json', to: 'users#show_users_json', :defaults => { :format => 'json' }
  get '/show_user_json/:id', to: 'users#show_user_json', :defaults => { :format => 'json' }
  resources :relationships, only: [:create,:destroy]
  resources :ratings, only: [:create]

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

end

app/models/user.rb
class User < ApplicationRecord
  has_many :micro_posts, dependent: :destroy
  has_many :active_relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  has_many :following, through: :active_relationships, source: :followed
  has_many :passive_relationships, class_name: "Relationship",
           foreign_key: "followed_id", dependent: :destroy
  has_many :followers, through: :passive_relationships, source: :follower
  attr_accessor :activation_token, :reset_token
  before_save :email_downcase
  before_create :create_activation_digest
  validates :name, presence: true, length: {maximum: 50}
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
  validates :user, presence: true, length: {maximum: 255}, format: {with: VALID_EMAIL_REGEX}, uniqueness: {case_sensitive: false}
  validates :password, :format => {:with => /\A(?=.*\d)(?=.*([a-z]|[A-Z]))([\x20-\x7E]){8,40}\z/, message: "must be at least 6 characters and include one number and one letter."},
            :presence => true,
            :confirmation => true,
            :length => {:within => 5..40},
            :on => [:create, :update], allow_nil: true
  has_secure_password

  def authenticated?(attribute, token)
    digest = send("#{attribute}_digest")
    return false if digest.nil?
    BCrypt::Password.new(digest).is_password?(token)
  end

  def create_reset_digest
    self.reset_token = User.new_token
    update_columns(reset_digest: User.digest(reset_token), reset_sent_at: Time.zone.now)
  end

  def reset_token_expired?
    reset_sent_at < 10.minutes.ago
  end

  def send_password_reset_mail
    UserMailer.password_reset(self).deliver_now
  end


  def activate
    update_attributes(activated: true, activated_at: Time.zone.now)
    # update_attribute(:activated,    true)
    # update_attribute(:activated_at, Time.zone.now)
  end

  def send_mail
    UserMailer.account_activation(self).deliver_now
  end

  #for showing all microposts
  def feed
    following_ids = "SELECT followed_id FROM relationships WHERE follower_id = :user_id"
    MicroPost.where("user_id IN (#{following_ids}) OR user_id = :user_id", user_id: id) # for avoiding sql injection  , normally following_ids contain the list of all users followed by default but we are using query to improve performance
  end

  def follow(other_user)
    following << other_user
  end

  def unfollow(other_user)
    following.delete(other_user)
  end

  def following?(other_user)
    following.include?(other_user)
  end

  def self.search(search)
    where("name LIKE ?", "%#{search}%")
  end

  class << self

    def User.digest(string)
      cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
          BCrypt::Engine.cost
      BCrypt::Password.create(string, cost: cost)
    end

    def User.new_token
      SecureRandom.urlsafe_base64
    end

  end

  private

  def email_downcase
    self.user = user.downcase
  end

  def create_activation_digest
    self.activation_token= User.new_token
    self.activation_digest= User.digest(activation_token)
  end

end

app/controllers/api/v1/users_controller.rb
module Api
  module V1
    class UsersController < ApplicationController
      respond_to :json

      def index
        # render json: {user: User.all}
        respond_with User.all
      end

      def show
        respond_with User.find(params[:id])
      end


      def destroy
        respond_with User.destroy(params[:id])

      end
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :logged_in_user , only: [:index,:edit,:update,:destroy,:show,:following,:followers]
  before_action :correct_user , only: [:edit, :update]
  before_action :is_admin?, only: [:destroy]
  before_action :check_old_password, only: [:update]
  # skip_before_action :verify_authenticity_token, :if => Proc.new { |c| c.request.format == 'application/json' }


  def index
    if params[:search]
      @users = User.paginate(page: params[:page], :per_page => 10).search(params[:search]).order("created_at DESC")
      if @users.blank?
        flash[:info] = "No users with name containing #{params[:search]}"
        @users = User.paginate(page: params[:page], :per_page => 10).where(activated: true)
      end
    else
      @users = User.paginate(page: params[:page], :per_page => 10).where(activated: true)
    end
  end
# for Json Api
  def show_users_json
    @users = User.all
    # respond_to do |format|
    #   format.json {}
    # end
  end
  def show_user_json
    @user = User.find(params[:id])
    @microposts = @user.micro_posts.all;
    # respond_to do |format|
    #   format.json {}
    # end
  end

  def new
    @user = User.new
  end

  def show
    @user = User.find(params[:id])
    @microposts = @user.micro_posts.paginate(page: params[:page], :per_page => 10)
    if !@user.activated
      flash[:warning] = "User account is not yet active"
      redirect_to root_url
    end
  end

  def create
    @user = User.new(user_params)
    if @user.save
      @user.send_mail
      flash[:info] = "Please check your email to activate your account."
      respond_to do |format|
      format.html {redirect_to root_url}
      format.json {redirect_to login_url }
      end
    else
      render 'new'
    end

  end

  def edit
    @user = User.find(params[:id])
  end


  def update
    @user = User.find(params[:id])
    if @user.update_attributes(user_params)
      flash[:success] = "Your Details have been Updated Successfully " + @user.name + " !"
      respond_to do |format|
        format.html {redirect_to root_url}
        format.json {redirect_to root_path }
      end
    else
      render 'edit'
    end
  end

  def destroy
    if is_admin? && !User.find(params[:id]).superadmin?
      User.find(params[:id]).destroy
      flash[:success] = "User has been Deleted Successfully"
      respond_to do |format|
        format.html {redirect_to users_path}
        format.json {render :json => {:name => "David"}.to_json}
      end
    else
      flash[:danger] = "You will be severely punished"
      redirect_to root_path
    end
  end



  #For making the user as ADMIN
    def make_admin
      if is_superadmin?
        @user = User.find(params[:id])
        if params[:status] == "undo"
          @user.update_attributes(admin:false)
          flash[:info] = "Removed admin status for #{@user.name}"
          redirect_to users_path
        elsif @user.update_attributes(admin:true)
          flash[:success] = "#{@user.name} has been made as admin"
          redirect_to users_path
        end
      end
    end

  def following
    @title = "Following"
    @user = User.find(params[:id])
    @users = @user.following.paginate(page: params[:page],per_page: 10)
    @all_users = @user.following.all
    respond_to do |format|
      format.html {render 'show_follow'}
      format.pdf do
        pdf = FollowersPdf.new(@all_users,"Followings")
        send_data pdf.render, filename: "followings_#{@user.name}.pdf", type: 'application/pdf'
      end
      format.json {}
    end
  end

  def followers
    @title = "Followers"
    @user = User.find(params[:id])
    @users = @user.followers.paginate(page: params[:page],per_page: 10)
    @all_users = @user.followers.all  # for pdf
    respond_to do |format|
      format.html {render 'show_follow'}
      format.pdf do
        pdf = FollowersPdf.new(@all_users,"Followers")
        send_data pdf.render, filename: "followers_#{@user.name}.pdf", type: 'application/pdf'
      end
      format.json {}
    end
  end

  private

    def user_params
      params.require(:user).permit(:name,:user,:password,:password_confirmation)
    end

  #Before Filters

    def correct_user
      @user = User.find(params[:id])
       unless current_user?(@user)
         redirect_to root_path
         flash[:warning] = "You dont have access rights to update this record"
       end
    end

    def is_admin?
      current_user.admin?
    end

    def is_superadmin?
      current_user.superadmin?
    end

   def check_old_password
    if  @user.authenticated?(:password,params[:user][:password])
      flash[:warning] = "Please use new password"
      render 'edit'
    end
    end

end

app/helpers/users_helper.rb
module UsersHelper

  def gravatar_for(user, size:80)
    gravatar_id = Digest::MD5::hexdigest(user.user.downcase)
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end

end

app/views/users/_follow.html.erb
<%= form_for(current_user.active_relationships.build,remote: true) do |f| %>
  <div>
    <%= hidden_field_tag :followed_id,@user.id %>
  </div>
  <%= f.submit "Follow", class: "btn btn-warning" %>
<% end %>

app/views/users/_follow_form.html.erb
<% unless current_user?(@user) %>
  <div id="follow_form">
    <% if current_user.following?(@user) %>
     <%= render 'unfollow' %>
    <% else %>
      <%= render 'follow' %>
    <% end %>
  </div>
<% end %>

app/views/users/_unfollow.html.erb
<%= form_for(current_user.active_relationships.find_by(followed_id: @user.id), html: { method: :delete}, remote:true) do |f|%>
  <%= f.submit "Unfollow", class: "btn btn-danger" %>
<% end %>

app/views/users/_user.html.erb
<li>
  <%= gravatar_for user, size:50 %>
  <%= link_to user.name, user %>
  <% if current_user.superadmin && !current_user?(user)  && !user.superadmin %>
      <%if user.admin? %>
         | <%= link_to " Undo Admin",makeadmin_path(:id => user.id,:status => 'undo'),method: :patch,:style => "color:green",data: {confirm: "Are you Sure?"}%>
      <% else %>
      | <%= link_to " Make Admin", makeadmin_path(:id => user.id,:status => ''), method: :patch,:style => "color:green",data: {confirm: "Are you Sure?"} %>
      | <%= link_to " Delete", user, method: :delete,:style => "color:red",data: {confirm: "Are you Sure?"} %>
      <% end %>
  <% elsif current_user.admin && !current_user?(user) && (!user.admin? && !user.superadmin?)%>  <!-- checks whether the operationg person is an admin and current user is not the user i.e, he is not deleting himself and he cannot delete other admins -->
  | <%= link_to " Delete", user , method: :delete , :style => "color:red",data: {confirm: "Are you Sure?"} %>
  <% end %>
</li>

app/views/users/edit.html.erb
<% provide(:title,"Edit User") %>
<% provide(:button_name,"Save Changes") %>
<h1> Update Your Profile </h1>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= render 'shared/form' %>
    <div class="gravatar_edit">
      <%= gravatar_for @user %>
      <a href="http://gravatar.com/emails" target="_blank" rel="noopener">change</a>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<% provide(:title,"Users") %>
<h1> All users </h1>
<%= form_tag(users_path,method: :get, id:"Search-form",style: "float:right;") do %>
    <%= text_field_tag :search, params[:search], placeholder: "Search Dobble user", style: "float:left;width:initial" %>
    <%= submit_tag "Search", :name => nil, style: "float:left;width: initial;height: 24px;"%>
<% end %>
<%= will_paginate %>
<ul class="users">
  <% @users.each do |user| %>
    <%= render user %>            <!-- we can also use render @users -->
  <% end %>
</ul>
<%= will_paginate %>

app/views/users/new.html.erb
<% provide(:title,"Signup page") %>
<% provide(:button_name,"Create my Account") %>
<h1>Users - Signup Page</h1>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= render 'shared/form'%>
  </div>
</div>

app/views/users/show.html.erb
<% provide(:title,@user.name + " Profile") %>
<div class=row">
<div class="col-md-4">
  <%= gravatar_for @user %>
  <b> <%= @user.name %></b>
</div>
<div class="col-md-8">
<table class="table">
  <thead>
  <tr>
    <th>Firstname</th>
    <th>Email</th>
    <th>Created at</th>
    <th>Updated at</th>
    <th>Current Time</th>
  </tr>
  </thead>
  <tbody>
  <tr class="success">
    <td><%= @user.name %></td>
    <td><%= @user.user %></td>
    <td><%= @user.created_at %></td>
    <td><%= @user.updated_at %></td>
    <td><%= Time.now%></td>
  </tr>
  </tbody>
</table>
</div>
</div>
<div class="row">
  <div class="col-md-8 col-md-offset-4">
    <%= render 'follow_form' if logged_in? %>
    <%= will_paginate @microposts %>
    <% if @microposts.any? %>
            <%= render 'micro_posts/micropost' %>
    <% end %>
    <%= will_paginate @microposts %>
  </div>
</div>

app/views/users/show_follow.html.erb
<% provide(:title ,@title) %>
<div class="row">
  <div class="col-md-4">
    <div style="float:left"><%= gravatar_for(@user,size: 10) %></div>
    <p class="show_name"><%=@user.name %>, <%= @user.micro_posts.count %> Posts</p>
  </div>
  <div class="col-md-8">
    <%= render 'shared/stats' %>
    <%if @users.any? %>
    <h3 class="follow-heading"><%= @title %></h3>
        <p style="float: right; font-size: large"><% if (@title == "Following" ) %><%= link_to "Download PDF", following_user_path(@user, :format => 'pdf'),style: "color:darkcyan" %>
              <% else %> <%= link_to "Download PDF", followers_user_path(@user, :format => 'pdf'), style: "color:darkcyan" %><% end %></p>
    <ul class="users follow">
      <% @users.each do |user| %>
        <%= render user %>
      <% end %>
    </ul>
    <%= will_paginate %>
    <% end %>
  </div>

</div>