config/routes.rb
Rails.application.routes.draw do

  resources :topics
  namespace :api, defaults: {format: 'json'} do
    namespace :v1 do
      resources :users
    end
  end

  root "pages#homepage"
  get '/home',to: 'pages#homepage'
  get '/help', to: 'pages#helppage'
  get '/about', to: 'pages#aboutpage'
  get '/contact',to: 'pages#contactpage'
  get '/signup',to: 'users#new'
  post '/signup',  to: 'users#create'
  patch '/makeadmin', to: 'users#make_admin', as: 'makeadmin'
  get '/login', to:  'sessions#new'
  post '/login', to:  'sessions#create'
  delete  '/logout', to:  'sessions#destroy'
  resources :account_activations, only: [:edit]
  resources :users  do
    member do
      get :following # like users/1/following
      get :followers
    end
  end
  resources :password_resets, only: [:new,:create,:edit,:update]
  resources :micro_posts, only: [:create,:destroy]
  get '/micro_posts', to: 'micro_posts#index', :defaults => { :format => 'json' }
  get '/show_users_json', to: 'users#show_users_json', :defaults => { :format => 'json' }
  get '/show_user_json/:id', to: 'users#show_user_json', :defaults => { :format => 'json' }
  resources :relationships, only: [:create,:destroy]
  resources :ratings, only: [:create]

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

end

app/views/pages/aboutpage.html.erb
<% provide(:title, "Aboutpage") %>
<!DOCTYPE html>
<html>

<body>
<h1>This is about Page</h1>
<p> This is created by SAI RAM REDDY. You can find him <a href="http://www.sairam.esy.es"> here.</a></p>
</body>
</html>

app/views/pages/contactpage.html.erb
<% provide(:title , "Contactpage") %>
<h1>
  contact page
</h1>
  <label>
    Phone Number:
  </label>
  <p>
    7418387456
  </p>

app/views/pages/helppage.html.erb
<% provide(:title, "Helppage") %>
<div class="row">
  <h1>Contact</h1>
  <div class="col-md-5 col-md-offset-4">
    <p>Sairam reddy blog can be found at
      <a href="http://www.sairam.esy.es">SAIRAMREDDY BLOG</a></p>
  </div>
</div>

app/views/pages/homepage.html.erb
<% if logged_in? %>
    <div class="row">
      <section class="stats">
        <%= render 'shared/stats' %>
      </section>
      <div id="formDiv">
      <%= form_for(@micropost,:url => micro_posts_path,:method => :post, remote: true) do |f|%>
          <div id="errorDisplay">
          <%= render 'shared/error',object: f.object %>
          </div>
          <div class="panel panel-default">
          <div class="panel-heading">
            <h3 class="panel-title">Whats on your mind</h3>
          </div>
          <div class="panel-body">
            <div class="col-md-2">
              <%= gravatar_for(current_user,size: 10) %>
            </div>
            <div class="col-md-10">
              <%= f.text_area :content,rows: 4, placeholder: "Compose new micropost...",id: "tweet-content" %>
              <%= f.file_field :Picture, accept: 'image/jpeg,image/gif,image/png', id: "tweet-picture" ,style:'float:left;width: 250px;height: 31px;padding-top: 3px;border-style: hidden;'%>

              <%= f.radio_button :topic_id, 1 %>
              <%= f.label :Sports %>

              <%= f.radio_button :topic_id, 2 %>
              <%= f.label :Movies%>

              <%= f.radio_button :topic_id, 3 %>
              <%= f.label :Education %>


              <%= f.radio_button :topic_id, 4 %>
              <%= f.label :Gossips%>
              <%= f.submit "Post", class: "btn btn-primary", :style=> 'width: 70px;float:right' %>

            </div>
          </div>
        </div>
      <% end %>
      </div>
     <%= render 'shared/display_modal' %>
    </div>
    <div id="show_feeds">
      <% provide(:heading,"Your Feed") %>
      <%= render 'shared/show_feeds' %>
    </div>
<% else %>
  <div class="jumbotron">
    <div class="container">
      <h1>Welcome to Dobble</h1>
      <h2>
        A new way of connecting with people
      </h2>
      <%= link_to "Sign up Now!", signup_path, class: "btn btn-lg btn-primary" %>
      <% if @device.include? "Android"%>
      <% url = "http://play.google.com/store/apps?id=com.google.android.apps.maps" %>
      <%= link_to image_tag("icon_google_play.png") , url %>
      <% end %>
    </div>
  </div>
<h1>Developed using Rails</h1>
<p>SAIRAM REDDY BLOG
   <a href = "http://www.sairam.esy.es">BLOG</a>. He studied at <a href="http://www.sastra.edu">SASTRA</a> </p>
<%end%>