config/routes.rb
Rails.application.routes.draw do

  resources :topics
  namespace :api, defaults: {format: 'json'} do
    namespace :v1 do
      resources :users
    end
  end

  root "pages#homepage"
  get '/home',to: 'pages#homepage'
  get '/help', to: 'pages#helppage'
  get '/about', to: 'pages#aboutpage'
  get '/contact',to: 'pages#contactpage'
  get '/signup',to: 'users#new'
  post '/signup',  to: 'users#create'
  patch '/makeadmin', to: 'users#make_admin', as: 'makeadmin'
  get '/login', to:  'sessions#new'
  post '/login', to:  'sessions#create'
  delete  '/logout', to:  'sessions#destroy'
  resources :account_activations, only: [:edit]
  resources :users  do
    member do
      get :following # like users/1/following
      get :followers
    end
  end
  resources :password_resets, only: [:new,:create,:edit,:update]
  resources :micro_posts, only: [:create,:destroy]
  get '/micro_posts', to: 'micro_posts#index', :defaults => { :format => 'json' }
  get '/show_users_json', to: 'users#show_users_json', :defaults => { :format => 'json' }
  get '/show_user_json/:id', to: 'users#show_user_json', :defaults => { :format => 'json' }
  resources :relationships, only: [:create,:destroy]
  resources :ratings, only: [:create]

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>I am sairam reddy from sastra university</small>
  <nav>
    <ul>
      <li><%= link_to "about" , about_path %></li>
      <li><%= link_to "help" , help_path %></li>
      <li><%= link_to "contact", contact_path %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_head.html.erb
<head>
  <title> <%= full_title(yield(:title)) %></title>
  <%= csrf_meta_tags %>
  <script
  src="https://code.jquery.com/jquery-3.2.1.js"
  integrity="sha256-DZAnKJ/6XZ9si04Hgrsxu/8s717jcIzLy3oi35EouyE="
  crossorigin="anonymous"></script>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  <%= render 'layouts/shim' %>
</head>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "Dobble", root_path , id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%=link_to "Home", root_path%></li>
        <li><%=link_to "Help", help_path%></li>
        <li><%=link_to "Topics", topics_path %></li>
        <% if logged_in? %>
            <li><%= link_to "Users" , users_path %></li>
            <div class="btn-group" style="padding-top: 8px;">
              <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
               <%=  current_user.name %><span class="caret"></span>
              </button>
              <ul class="dropdown-menu">
                <li><%= link_to "Profile", current_user %> </li>
                <li><%= link_to "settings" , edit_user_path(current_user) %></li>
                <li role="separator" class="divider"></li>
                <li><%= link_to "Logout", logout_path, method: :delete %></li>
              </ul>
            </div>
        <% else %>
            <li><%= link_to "Log in", login_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
</script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<%= render 'layouts/head' %>
<body>
<%= render 'layouts/header' %>
<div class="container">
  <% flash.each do |key,value|  %>
    <div class="container">
      <%= content_tag(:div,value,class:"alert alert-#{key}") %>
    </div>
  <%end%>
  <%= yield %>
</div>
<%= render 'layouts/footer' %>
<%= debug(params) if Rails.env.development? %>
</body>
</html>